"""
SYNTHETIC FALSIFIABILITY TEST -- the central Milestone-1 demonstration.

This is a NUMERICAL DEMONSTRATION on synthetic data, not an empirical
physical result (see docs/software_scope.md and docs/epistemic_tiers.md).
It exercises the shared-V family test (docs/protocol.md, Step 5, route 1;
falsifiability.shared_V_family_test) end to end:

Case A (genuine shared potential): two trajectories are numerically
integrated from the SAME autonomous potential V(chi) = 1/2 * chi^2 at two
different conserved energies. Their reconstructed U_k(chi) curves must
collapse onto a common curve within a small residual.

Case B (deliberately mismatched potentials): one trajectory from
V(chi) = 1/2 * chi^2 and one from a DIFFERENT potential
V(chi) = 1/4 * chi^4 are incorrectly asked to share a single V(chi). The
residual must be materially larger than Case A's.

The mandatory property this file exists to enforce: a bug that always
reports agreement -- e.g. shared_V_family_test always returning a tiny
residual regardless of input -- MUST cause these tests to fail. The
mismatched case is therefore asserted explicitly to be large, not merely
"not small"; see test_mismatched_family_residual_is_materially_larger and
test_mismatch_residual_relationally_dwarfs_shared_residual.

Trajectories are generated by numerically integrating the exact equation
of motion implied by conserved energy on the Fisher kinetic structure,
    (dchi/dx)^2 = 2 * (E - V(chi)) * (1 - chi^2),
via scipy.integrate.solve_ivp (tight tolerances), then normal_form and
falsifiability consume ONLY (x, chi, E) -- the same inputs a real
trajectory would supply. No paper's reported residual value is hard-coded
here; the actual residuals obtained are asserted against generous,
order-of-magnitude bounds and printed via the assertion messages below and
in the accompanying implementation report.
"""

import numpy as np
import pytest
from scipy.integrate import solve_ivp

from constraint_geometry.normal_form import extract_normal_form
from constraint_geometry.falsifiability import (
    FamilyMember,
    shared_V_family_test,
    heldout_V_test,
    pass_fail,
)

# ---------------------------------------------------------------------------
# Synthetic trajectory generator (test infrastructure only -- not part of
# the constraint_geometry package, since it encodes a *specific* domain
# model (a chosen V(chi)) rather than exact coordinate algebra).
# ---------------------------------------------------------------------------


def _make_orbit(V, E, chi0, chi_cap, n):
    """Integrate dchi/dx = sqrt(2*(E-V(chi))*(1-chi^2)) from chi(0)=chi0
    until chi reaches chi_cap, then resample n points strictly inside
    (chi0, chi_cap) (stopping just short of the cap, since the normal-form
    boundary guard rejects |chi| >= 1 and the cap itself is an event, not
    a sample point)."""

    def rhs(x, y):
        chi = y[0]
        val = 2.0 * (E - V(chi)) * (1.0 - chi**2)
        return [np.sqrt(max(val, 0.0))]

    def hit_cap(x, y):
        return y[0] - chi_cap

    hit_cap.terminal = True
    hit_cap.direction = 1

    probe = solve_ivp(
        rhs, [0.0, 100.0], [chi0], events=hit_cap,
        rtol=1e-12, atol=1e-14, method="RK45", max_step=0.01,
    )
    assert probe.t_events[0].size == 1, "orbit did not reach chi_cap; adjust parameters"
    x_max = float(probe.t_events[0][0]) * 0.999

    x = np.linspace(0.0, x_max, n)
    sol = solve_ivp(
        rhs, [0.0, x_max], [chi0], t_eval=x,
        rtol=1e-12, atol=1e-14, method="RK45",
    )
    return sol.t, sol.y[0]


def _member_from_orbit(V, E, chi0, chi_cap, n, label):
    x, chi = _make_orbit(V, E, chi0, chi_cap, n)
    nf = extract_normal_form(x, chi)  # numerical derivative, real pipeline
    return FamilyMember(chi=nf.chi, dchi_dx=nf.dchi_dx, E=E, label=label)


V_SHARED = lambda chi: 0.5 * chi**2         # V(chi) = 1/2 chi^2
V_OTHER = lambda chi: 0.25 * chi**4          # V(chi) = 1/4 chi^4 -- different potential
N_SAMPLES = 4000
CHI_CAP = 0.9


@pytest.fixture(scope="module")
def shared_potential_members():
    """Two orbits of the SAME potential V(chi) = 1/2 chi^2 at different
    conserved energies -- Case A."""
    m1 = _member_from_orbit(V_SHARED, E=1.0, chi0=-0.6, chi_cap=CHI_CAP,
                             n=N_SAMPLES, label="orbit1 (V_shared, E=1.0)")
    m2 = _member_from_orbit(V_SHARED, E=1.5, chi0=0.2, chi_cap=CHI_CAP,
                             n=N_SAMPLES, label="orbit2 (V_shared, E=1.5)")
    return m1, m2


@pytest.fixture(scope="module")
def mismatched_potential_members(shared_potential_members):
    """orbit1 (from V_shared) paired against an orbit of a genuinely
    DIFFERENT potential V(chi) = 1/4 chi^4 -- Case B."""
    m1, _ = shared_potential_members
    m3 = _member_from_orbit(V_OTHER, E=0.6, chi0=0.1, chi_cap=CHI_CAP,
                             n=N_SAMPLES, label="orbit3 (V_other, E=0.6)")
    return m1, m3


class TestCaseA_SharedPotentialCollapses:
    def test_shared_family_residual_is_small(self, shared_potential_members):
        result = shared_V_family_test(list(shared_potential_members), n_grid=300)
        # Generous bound: two orbits of the same autonomous potential,
        # reconstructed via a real (finite-difference) normal-form
        # extraction at n=4000 samples, collapse to residual_max ~5e-4 in
        # practice (see implementation report for the exact value
        # obtained). 1e-2 leaves ample margin while still being tight
        # enough that a broken implementation would not pass it.
        assert result.residual_max < 1e-2, (
            f"expected small collapse residual for a genuine shared "
            f"potential, got residual_max={result.residual_max!r}"
        )
        assert result.residual_rms < result.residual_max

    def test_shared_family_passes_a_declared_threshold(self, shared_potential_members):
        # Demonstrates the required no-default-threshold API: the
        # threshold is supplied explicitly by the caller (here, the test),
        # never assumed by the library.
        result = shared_V_family_test(list(shared_potential_members), n_grid=300)
        declared_threshold = 1e-2
        assert pass_fail(result, declared_threshold) is True


class TestCaseB_MismatchedPotentialsAreRejected:
    def test_mismatched_family_residual_is_materially_larger(
        self, mismatched_potential_members
    ):
        result = shared_V_family_test(list(mismatched_potential_members), n_grid=300)
        # V_other differs from V_shared by an O(1) amount over the
        # comparison domain, so the collapse must fail by an O(1) margin,
        # not merely "slightly more than Case A".
        assert result.residual_max > 1e-2, (
            f"expected a materially large residual for genuinely different "
            f"potentials, got residual_max={result.residual_max!r}"
        )

    def test_mismatched_family_fails_the_same_declared_threshold(
        self, mismatched_potential_members
    ):
        result = shared_V_family_test(list(mismatched_potential_members), n_grid=300)
        declared_threshold = 1e-2  # the same threshold Case A passed
        assert pass_fail(result, declared_threshold) is False


class TestPassFailHasNoDefaultThreshold:
    """docs/software_scope.md's core API guarantee: pass_fail's threshold
    is a required positional argument with no default anywhere in the
    package. This is enforced by Python's own signature machinery, not by
    a runtime check inside the function -- so the correct proof is that
    omitting it raises TypeError naturally, before pass_fail's body ever
    runs."""

    def test_missing_threshold_raises_typeerror(self, shared_potential_members):
        result = shared_V_family_test(list(shared_potential_members), n_grid=300)
        with pytest.raises(TypeError):
            pass_fail(result)  # no threshold supplied -- must fail to call

    def test_signature_has_no_default_for_threshold(self):
        import inspect

        sig = inspect.signature(pass_fail)
        threshold_param = sig.parameters["threshold"]
        assert threshold_param.default is inspect.Parameter.empty, (
            "pass_fail's threshold parameter must not have a default; "
            f"found default={threshold_param.default!r}"
        )


class TestFalsifiabilityIsReal:
    """The property Section 6 requires as essential: the test must be
    able to fail, and a bug that always reports agreement must be caught."""

    def test_mismatch_residual_relationally_dwarfs_shared_residual(
        self, shared_potential_members, mismatched_potential_members
    ):
        shared_result = shared_V_family_test(list(shared_potential_members), n_grid=300)
        mismatch_result = shared_V_family_test(
            list(mismatched_potential_members), n_grid=300
        )
        ratio = mismatch_result.residual_max / shared_result.residual_max
        # A relational assertion, not just two absolute bounds: guards
        # against a degenerate implementation that is merely "small" and
        # "large" by coincidence rather than actually discriminating.
        assert ratio > 50.0, (
            f"expected the mismatched-family residual to dwarf the "
            f"shared-family residual; got shared={shared_result.residual_max!r}, "
            f"mismatch={mismatch_result.residual_max!r}, ratio={ratio!r}"
        )

    def test_identical_member_list_gives_zero_residual(self, shared_potential_members):
        # Sanity floor: comparing a member against itself must give an
        # exactly-zero residual, confirming shared_V_family_test is not
        # silently inflating or deflating agreement.
        m1, _ = shared_potential_members
        result = shared_V_family_test([m1, m1], n_grid=300)
        assert result.residual_max == pytest.approx(0.0, abs=1e-15)


class TestHeldOutPrediction:
    """Minimal held-out demonstration (docs/protocol.md, Step 5, route 2).
    A third orbit of V_shared, not used to form the fit curve, should be
    predicted with a residual of the same order as the fit agreement
    itself."""

    def test_heldout_orbit_of_shared_potential_predicted_well(
        self, shared_potential_members
    ):
        m1, m2 = shared_potential_members
        m_heldout = _member_from_orbit(
            V_SHARED, E=2.0, chi0=-0.3, chi_cap=CHI_CAP, n=N_SAMPLES,
            label="orbit4 (V_shared, E=2.0, held out)",
        )
        result = heldout_V_test([m1, m2], m_heldout, n_grid=300)
        assert result.prediction_residual_max < 1e-2
        # The held-out prediction should not be dramatically worse than
        # the internal agreement of the fit members it was derived from.
        assert result.prediction_residual_max < 10.0 * result.fit_agreement.residual_max
